name: expressboilerplate

on:
  push:
    branches: [main]

  # pull_request:
  #   branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker test image
        run: docker build -t test-boilerplate . --target test

      - name: Run docker test image
        run: docker run test-boilerplate

      - name: Build docker test image
        run: docker build -t test-boilerplate . --target prod

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [test, build]
  #   steps:
  #     - name: Deploy appservice
  #       run: |
  #        # deploy to acr
